# Generated by Django 5.2.15 on 2026-08-09 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/%Y/%m/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.topic')),
            ],
            options={
                'verbose_name': 'Bilgi kartı',
                'verbose_name_plural': 'Bilgi kartları',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
