# Generated by Django 5.2.15 on 2026-08-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_topic_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_e',
            field=models.CharField(max_length=500),
        ),
    ]
