# Generated by Django 5.2.15 on 2026-08-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_option_e_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Başlık')),
                ('body', models.TextField(verbose_name='Metin')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('push_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Bildirim gönderildi')),
                ('push_success_count', models.PositiveIntegerField(default=0)),
                ('push_fail_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('other', 'Diğer')], default='android', max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cihaz jetonu',
                'verbose_name_plural': 'Cihaz jetonları',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
