# Generated by Django 5.2.15 on 2026-08-09 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_content_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sub', models.CharField(max_length=128, unique=True, verbose_name='Google kimlik')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='E-posta')),
                ('display_name', models.CharField(blank=True, max_length=160, verbose_name='Ad')),
                ('photo_url', models.URLField(blank=True, max_length=512)),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('premium_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Premium bitiş')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('api_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='API jetonu')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Son giriş')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uygulama kullanıcısı',
                'verbose_name_plural': 'Uygulama kullanıcıları',
                'ordering': ['-last_login_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='content.appuser', verbose_name='Kullanıcı'),
        ),
    ]
