# Generated by Django 5.2.15 on 2026-08-09 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_question_map_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Yıldız')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='İlk puan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='content.question', verbose_name='Soru')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_ratings', to='content.appuser', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Soru puanı',
                'verbose_name_plural': 'Soru puanları',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['question', 'stars'], name='rating_question_stars_idx')],
                'constraints': [models.UniqueConstraint(fields=('question', 'user'), name='unique_question_rating_per_user'), models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 5)), name='question_rating_stars_between_1_and_5')],
            },
        ),
    ]
