# Generated by Django 5.1 on 2026-08-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_correct_ales_dgs_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Büyük/küçük harf duyarsız; kayıtta otomatik büyük harfe çevrilir.",
                        max_length=32,
                        unique=True,
                        verbose_name="Kod",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Yalnızca admin panelinde görünür.",
                        max_length=120,
                        verbose_name="Başlık",
                    ),
                ),
                (
                    "max_redemptions",
                    models.PositiveIntegerField(
                        help_text="Bu koddan yararlanabilecek en fazla kişi sayısı.",
                        verbose_name="Maksimum kullanım",
                    ),
                ),
                (
                    "premium_duration_days",
                    models.PositiveIntegerField(
                        help_text="Kodu kullanan her kullanıcıya tanınan premium gün sayısı.",
                        verbose_name="Premium süresi (gün)",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Boş bırakılırsa hemen kullanılabilir.",
                        null=True,
                        verbose_name="Geçerlilik başlangıcı",
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        help_text="Bu tarihten sonra kod kullanılamaz.",
                        verbose_name="Geçerlilik bitişi",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Promosyon kodu",
                "verbose_name_plural": "Promosyon kodları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoCodeRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kullanım zamanı"),
                ),
                (
                    "premium_expires_at",
                    models.DateTimeField(
                        help_text="Kullanım anında hesaplanan bitiş tarihi.",
                        verbose_name="Verilen premium bitişi",
                    ),
                ),
                (
                    "promo_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="content.promocode",
                        verbose_name="Promosyon kodu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_redemptions",
                        to="content.appuser",
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promosyon kullanımı",
                "verbose_name_plural": "Promosyon kullanımları",
                "ordering": ["-redeemed_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="promocoderedemption",
            constraint=models.UniqueConstraint(
                fields=("promo_code", "user"),
                name="unique_promo_redemption_per_user",
            ),
        ),
    ]
