# Generated by Django 5.1 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0019_promo_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="figure_tikz",
            field=models.TextField(
                blank=True,
                help_text="Geometri soruları için LaTeX TikZ çizim kodu.",
                verbose_name="Şekil kodu (TikZ)",
            ),
        ),
    ]
