# Generated by Django 5.1 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0020_question_figure_tikz"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="figure_tikz",
            new_name="figure_svg",
        ),
        migrations.AlterField(
            model_name="question",
            name="figure_svg",
            field=models.TextField(
                blank=True,
                help_text="Geometri soruları için SVG çizim kodu.",
                verbose_name="Şekil kodu (SVG)",
            ),
        ),
    ]
