# Generated by Django 5.2.15 on 2026-08-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_rename_figure_tikz_figure_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='content_type',
            field=models.CharField(choices=[('lisans', 'Lisans'), ('onLisans', 'Ön Lisans'), ('ortaogretim', 'Ortaöğretim')], default='lisans', help_text='Bu sınav için hangi müfredat (Lisans / Ön Lisans / Ortaöğretim) açılsın.', max_length=20, verbose_name='Soru bankası tipi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme'),
        ),
        migrations.AlterField(
            model_name='question',
            name='map_template',
            field=models.CharField(blank=True, choices=[('', 'Harita yok'), ('turkiye_goller', 'Türkiye — Tuz Gölü ve Van Gölü'), ('turkiye_indirgenmis_sicaklik', 'Yıllık ortalama indirgenmiş sıcaklık dağılışı')], default='', help_text='Koordinatlı harita sorusu şablonu.', max_length=32),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Son güncelleme'),
        ),
    ]
