# Generated by Django 5.2.15 on 2026-08-16 16:27

import content.map_catalog
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_questionerrorreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('marker', 'Koordinatlı işaret'), ('static', 'Tematik harita')], default='static', max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='maps/')),
                ('editor_image', models.ImageField(blank=True, help_text='Koordinatlı düzenleyici görseli; boşsa ana görsel kullanılır.', null=True, upload_to='maps/editor/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Harita şablonu',
                'verbose_name_plural': 'Harita şablonları',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='map_template',
            field=models.CharField(blank=True, choices=content.map_catalog.map_template_choices, default='', help_text='Koordinatlı harita sorusu şablonu.', max_length=64),
        ),
    ]
