# Generated by Django 5.2.15 on 2026-08-17 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_normalize_topic_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('correct', 'Doğru'), ('wrong', 'Yanlış'), ('blank', 'Boş')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='blank_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Kolay'), ('medium', 'Orta'), ('hard', 'Zor')], db_index=True, default='medium', max_length=12, verbose_name='Zorluk'),
        ),
        migrations.AddField(
            model_name='question',
            name='wrong_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'difficulty', 'is_published'], name='question_topic_difficulty_idx'),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.question'),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='content.appuser'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['question', 'outcome'], name='attempt_outcome_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionattempt',
            constraint=models.UniqueConstraint(fields=('question', 'user'), name='unique_question_attempt_per_user'),
        ),
    ]
