# Generated by Django 5.2.15 on 2026-08-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_a_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='option_e_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='selected_option',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1),
        ),
    ]
