# Generated by Django 5.2.15 on 2026-08-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_question_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_image_phash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Perceptual hash (16 hex) — düzenlenmiş görselleri de yakalar', max_length=16),
        ),
    ]
