# Generated by Django 5.2.15 on 2026-08-18 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_add_source_image_phash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrIngestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_image_phash', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('engine', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('duplicate_match', models.CharField(blank=True, default='', max_length=32)),
                ('ok', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('stem', models.TextField(blank=True, default='')),
                ('options', models.JSONField(blank=True, default=dict)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('issue_formula_missing', models.BooleanField(default=False)),
                ('issue_char_drift', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duplicate_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_duplicate_logs', to='content.question')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_ingest_logs', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_ingest_logs', to='content.topic')),
            ],
            options={
                'verbose_name': 'OCR ingest kaydı',
                'verbose_name_plural': 'OCR ingest kayıtları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['engine', '-created_at'], name='ocrlog_engine_created'), models.Index(fields=['ok', '-created_at'], name='ocrlog_ok_created'), models.Index(fields=['duplicate_match'], name='ocrlog_dup_match')],
            },
        ),
    ]
