# Generated by Django 5.2.15 on 2026-08-18 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_add_ocr_ingest_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocringestlog',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='ocringestlog',
            name='raw_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ocringestlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('fallback_success', 'Fallback Success')], db_index=True, default='success', max_length=24),
        ),
        migrations.AddField(
            model_name='ocringestlog',
            name='used_model',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='ocringestlog',
            index=models.Index(fields=['status', '-created_at'], name='ocrlog_status_created'),
        ),
    ]
