# Generated by Django 5.2.15 on 2026-08-18 14:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_extend_ocr_ingest_log_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=64, unique=True)),
                ('pack_kind', models.CharField(choices=[('full', 'Tam deneme'), ('branch', 'Branş paketi')], default='branch', max_length=16, verbose_name='Paket türü')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('exam_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Deneme sayısı')),
                ('time_limit_minutes', models.PositiveIntegerField(default=130, verbose_name='Süre (dk)')),
                ('price_display', models.CharField(blank=True, help_text='Örn. 149,99 ₺', max_length=32, verbose_name='Vitrin fiyatı')),
                ('play_product_id', models.CharField(blank=True, max_length=120, verbose_name='Play Store SKU')),
                ('is_published', models.BooleanField(default=False, verbose_name='Yayında')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_packs', to='content.examtype', verbose_name='Sınav tipi')),
                ('subject', models.ForeignKey(blank=True, help_text='Branş paketlerinde zorunlu; tam denemede boş.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_packs', to='content.subject', verbose_name='Branş dersi')),
            ],
            options={
                'verbose_name': 'Deneme paketi',
                'verbose_name_plural': 'Deneme paketleri',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExamPackExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Sıra')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='content.exampack', verbose_name='Paket')),
            ],
            options={
                'verbose_name': 'Paket denemesi',
                'verbose_name_plural': 'Paket denemeleri',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='ExamPackExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='content.exampackexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_pack_links', to='content.question')),
            ],
            options={
                'verbose_name': 'Paket soru sırası',
                'verbose_name_plural': 'Paket soru sıraları',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='exampackexam',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='exam_pack_exams', through='content.ExamPackExamQuestion', to='content.question'),
        ),
        migrations.CreateModel(
            name='ExamDistributionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Soru sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_templates', to='content.examtype', verbose_name='Sınav tipi')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_templates', to='content.subject', verbose_name='Ders')),
                ('topic', models.ForeignKey(blank=True, help_text='Boş bırakılırsa ders toplamı satırıdır.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_templates', to='content.topic', verbose_name='Konu')),
            ],
            options={
                'verbose_name': 'Deneme dağılım şablonu',
                'verbose_name_plural': 'Deneme dağılım şablonları',
                'ordering': ['exam_type__sort_order', 'subject__sort_order', 'topic__sort_order'],
                'constraints': [models.UniqueConstraint(fields=('exam_type', 'subject', 'topic'), name='unique_exam_distribution_template')],
            },
        ),
        migrations.AddConstraint(
            model_name='exampackexamquestion',
            constraint=models.UniqueConstraint(fields=('exam', 'question'), name='unique_exam_pack_exam_question'),
        ),
        migrations.AddConstraint(
            model_name='exampackexam',
            constraint=models.UniqueConstraint(fields=('pack', 'index'), name='unique_exam_pack_exam_index'),
        ),
    ]
