# Generated by Django 5.2.15 on 2026-08-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_appuser_display_name_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampack',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Kapalıysa mobil Dersler vitrininde görünmez.', verbose_name='Aktif'),
        ),
    ]
