# Generated by Django 5.2.15 on 2026-08-20 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_content_requires_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileuiconfig',
            name='wrong_notebook_bubble_label',
            field=models.CharField(default='YANLIŞ DEFTERİM', max_length=48, verbose_name='Balon metni'),
        ),
        migrations.AlterField(
            model_name='question',
            name='map_markers',
            field=models.JSONField(blank=True, default=list, help_text='Harita işaretleri (elips/daire) ve boyalı iller.'),
        ),
        migrations.CreateModel(
            name='TopicSummaryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('formula', 'Formül'), ('tip', 'Püf nokta'), ('osym', 'ÖSYM buradan sorar')], default='tip', max_length=16, verbose_name='Tür')),
                ('title', models.CharField(max_length=160, verbose_name='Başlık')),
                ('body', models.TextField(help_text='Kısa formül, kural veya ÖSYM ipucu.', verbose_name='Özet')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_cards', to='content.topic')),
            ],
            options={
                'verbose_name': 'Özet konu kartı',
                'verbose_name_plural': 'Özet konu kartları',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
