# Generated by Django 5.2.15 on 2026-08-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0061_tg_exam_announcement_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileuiconfig',
            name='studio_modules',
            field=models.JSONField(blank=True, default=dict, help_text='Modül anahtarı → aktif. Boş sözlük = tüm modüller açık.', verbose_name='Stüdyo modülleri'),
        ),
        migrations.AlterField(
            model_name='tgexam',
            name='announcement_push_sent_at',
            field=models.DateTimeField(blank=True, help_text='Başlangıçtan 2 saat önce otomatik FCM duyurusu.', null=True, verbose_name='Duyuru bildirimi gönderildi'),
        ),
        migrations.AlterField(
            model_name='tgexam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=130, verbose_name='Süre (dk)'),
        ),
    ]
