# Generated by Django 5.2.15 on 2026-08-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0062_alter_tgexam_mobileui_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_a_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_options/%Y/%m/', verbose_name='Şık A görseli'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_options/%Y/%m/', verbose_name='Şık B görseli'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_options/%Y/%m/', verbose_name='Şık C görseli'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_options/%Y/%m/', verbose_name='Şık D görseli'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_e_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_options/%Y/%m/', verbose_name='Şık E görseli'),
        ),
        migrations.AddField(
            model_name='question',
            name='options_are_images',
            field=models.BooleanField(db_index=True, default=False, help_text='Şıklar metin yerine kırpılmış görsellerle gösterilir.', verbose_name='Görsel şıklar'),
        ),
        migrations.AlterField(
            model_name='telegrambotsession',
            name='source_message_id',
            field=models.BigIntegerField(blank=True, help_text="Evet veya /iptal ile silinir; Hayır'da sohbette kalır", null=True, verbose_name='Telegram fotoğraf mesajı'),
        ),
    ]
