from django.urls import path

from . import panel_views

urlpatterns = [
    path("", panel_views.panel_home, name="panel_home"),
    path("kalite/", panel_views.panel_quality, name="panel_quality"),
    path(
        "incelenecek-sorular/",
        panel_views.panel_error_reports,
        name="panel_error_reports",
    ),
    path(
        "hata-bildirimi/<int:report_id>/durum/",
        panel_views.panel_error_report_status,
        name="panel_error_report_status",
    ),
    path(
        "onay-bekleyen-sorular/",
        panel_views.panel_pending_questions,
        name="panel_pending_questions",
    ),
    path(
        "onay-bekleyen-sorular/<int:question_id>/onayla/",
        panel_views.panel_pending_question_approve,
        name="panel_pending_question_approve",
    ),
    path(
        "onay-bekleyen-sorular/<int:question_id>/reddet/",
        panel_views.panel_pending_question_reject,
        name="panel_pending_question_reject",
    ),
    path("haritalar/", panel_views.panel_maps, name="panel_maps"),
    path(
        "haritalar/<slug:slug>/sil/",
        panel_views.panel_map_delete,
        name="panel_map_delete",
    ),
    path(
        "soru/hizli/",
        panel_views.panel_quick_question,
        name="panel_quick_question",
    ),
    path(
        "soru/manuel/",
        panel_views.panel_manual_question,
        name="panel_manual_question",
    ),
    path(
        "api/ocr-question/",
        panel_views.panel_ocr_question,
        name="panel_ocr_question",
    ),
    path(
        "ders/<int:subject_id>/konular/",
        panel_views.panel_topic_options,
        name="panel_topic_options",
    ),
    path(
        "konu/<int:topic_id>/testler/",
        panel_views.panel_test_options,
        name="panel_test_options",
    ),
    path(
        "ders/<int:subject_id>/",
        panel_views.panel_subject,
        name="panel_subject",
    ),
    path(
        "ders/<int:subject_id>/konu/yeni/",
        panel_views.panel_topic_edit,
        name="panel_topic_new",
    ),
    path(
        "ders/<int:subject_id>/konu/<int:topic_id>/duzenle/",
        panel_views.panel_topic_edit,
        name="panel_topic_edit",
    ),
    path(
        "ders/<int:subject_id>/konu/<int:topic_id>/sil/",
        panel_views.panel_topic_delete,
        name="panel_topic_delete",
    ),
    path(
        "ders/<int:subject_id>/konular/sirala/",
        panel_views.panel_topic_reorder,
        name="panel_topic_reorder",
    ),
    path(
        "konu/<int:topic_id>/toggle/",
        panel_views.panel_topic_toggle,
        name="panel_topic_toggle",
    ),
    path(
        "konu/<int:topic_id>/kapasite/",
        panel_views.panel_topic_capacity,
        name="panel_topic_capacity",
    ),
    path(
        "konu/<int:topic_id>/bilgi/yeni/",
        panel_views.panel_lesson_edit,
        name="panel_lesson_new",
    ),
    path(
        "konu/<int:topic_id>/bilgi/<int:lesson_id>/",
        panel_views.panel_lesson_edit,
        name="panel_lesson_edit",
    ),
    path(
        "bilgi/<int:lesson_id>/sil/",
        panel_views.panel_lesson_delete,
        name="panel_lesson_delete",
    ),
    path(
        "konu/<int:topic_id>/ozet/yeni/",
        panel_views.panel_summary_card_edit,
        name="panel_summary_card_new",
    ),
    path(
        "konu/<int:topic_id>/ozet/<int:card_id>/",
        panel_views.panel_summary_card_edit,
        name="panel_summary_card_edit",
    ),
    path(
        "ozet-kart/",
        panel_views.panel_summary_card_studio,
        name="panel_summary_card_studio",
    ),
    path(
        "ozet-kart/<int:card_id>/",
        panel_views.panel_summary_card_studio,
        name="panel_summary_card_studio_edit",
    ),
    path(
        "ozet/<int:card_id>/sil/",
        panel_views.panel_summary_card_delete,
        name="panel_summary_card_delete",
    ),
    path(
        "konu/<int:topic_id>/soru/yeni/",
        panel_views.panel_question_edit,
        name="panel_question_new",
    ),
    path(
        "konu/<int:topic_id>/soru/<int:question_id>/",
        panel_views.panel_question_edit,
        name="panel_question_edit",
    ),
    path(
        "soru/<int:question_id>/sil/",
        panel_views.panel_question_delete,
        name="panel_question_delete",
    ),
    path(
        "soru/<int:question_id>/kopyala/",
        panel_views.panel_question_copy,
        name="panel_question_copy",
    ),
    path(
        "konu/<int:topic_id>/soru/toplu-sil/",
        panel_views.panel_question_bulk_delete,
        name="panel_question_bulk_delete",
    ),
    path(
        "konu/<int:topic_id>/grup/yeni/",
        panel_views.panel_scenario_edit,
        name="panel_scenario_new",
    ),
    path(
        "konu/<int:topic_id>/grup/<int:scenario_id>/",
        panel_views.panel_scenario_edit,
        name="panel_scenario_edit",
    ),
    path(
        "grup/<int:scenario_id>/sil/",
        panel_views.panel_scenario_delete,
        name="panel_scenario_delete",
    ),
    path(
        "konu/<int:topic_id>/test/yeni/",
        panel_views.panel_test_edit,
        name="panel_test_new",
    ),
    path(
        "konu/<int:topic_id>/test/<int:test_id>/",
        panel_views.panel_test_edit,
        name="panel_test_edit",
    ),
    path(
        "test/<int:test_id>/sil/",
        panel_views.panel_test_delete,
        name="panel_test_delete",
    ),
    path(
        "duyuru/",
        panel_views.panel_announcement_list,
        name="panel_announcement_list",
    ),
    path(
        "duyuru/yeni/",
        panel_views.panel_announcement_edit,
        name="panel_announcement_new",
    ),
    path(
        "duyuru/<int:announcement_id>/",
        panel_views.panel_announcement_edit,
        name="panel_announcement_edit",
    ),
    path(
        "duyuru/<int:announcement_id>/sil/",
        panel_views.panel_announcement_delete,
        name="panel_announcement_delete",
    ),
    path(
        "duyuru/<int:announcement_id>/gonder/",
        panel_views.panel_announcement_send,
        name="panel_announcement_send",
    ),
    path(
        "mobil-arayuz/",
        panel_views.panel_mobile_ui,
        name="panel_mobile_ui",
    ),
    path(
        "mini-deneme-odulleri/",
        panel_views.panel_daily_mini_ranking,
        name="panel_daily_mini_ranking",
    ),
    path(
        "sinavlar/",
        panel_views.panel_exam_type_list,
        name="panel_exam_type_list",
    ),
    path(
        "sinavlar/yeni/",
        panel_views.panel_exam_type_edit,
        name="panel_exam_type_new",
    ),
    path(
        "sinavlar/<int:exam_id>/",
        panel_views.panel_exam_type_edit,
        name="panel_exam_type_edit",
    ),
    path(
        "sinavlar/<int:exam_id>/sil/",
        panel_views.panel_exam_type_delete,
        name="panel_exam_type_delete",
    ),
    path(
        "deneme-sablon/",
        panel_views.panel_exam_distribution_list,
        name="panel_exam_distribution_list",
    ),
    path(
        "deneme-sablon/yeni/",
        panel_views.panel_exam_distribution_edit,
        name="panel_exam_distribution_new",
    ),
    path(
        "deneme-sablon/<int:template_id>/",
        panel_views.panel_exam_distribution_edit,
        name="panel_exam_distribution_edit",
    ),
    path(
        "deneme-sablon/<int:template_id>/sil/",
        panel_views.panel_exam_distribution_delete,
        name="panel_exam_distribution_delete",
    ),
    path(
        "deneme-paket/",
        panel_views.panel_exam_pack_list,
        name="panel_exam_pack_list",
    ),
    path(
        "deneme-paket/yeni/",
        panel_views.panel_exam_pack_edit,
        name="panel_exam_pack_new",
    ),
    path(
        "deneme-paket/<int:pack_id>/",
        panel_views.panel_exam_pack_edit,
        name="panel_exam_pack_edit",
    ),
    path(
        "deneme-paket/<int:pack_id>/toggle/",
        panel_views.panel_exam_pack_toggle,
        name="panel_exam_pack_toggle",
    ),
    path(
        "deneme-paket/<int:pack_id>/sil/",
        panel_views.panel_exam_pack_delete,
        name="panel_exam_pack_delete",
    ),
    path("uygulama-durumu/", panel_views.panel_app_stats, name="panel_app_stats"),
    path("kullanicilar/", panel_views.panel_users, name="panel_users"),
    path(
        "kullanicilar/toplu-sil/",
        panel_views.panel_user_bulk_delete,
        name="panel_user_bulk_delete",
    ),
    path(
        "kullanicilar/misafirleri-temizle/",
        panel_views.panel_user_purge_guests,
        name="panel_user_purge_guests",
    ),
    path(
        "kullanici/<int:user_id>/premium/",
        panel_views.panel_user_grant_premium,
        name="panel_user_grant_premium",
    ),
    path(
        "kullanici/<int:user_id>/premium/kaldir/",
        panel_views.panel_user_revoke_premium,
        name="panel_user_revoke_premium",
    ),
    path("promosyon/", panel_views.panel_promo_list, name="panel_promo_list"),
    path(
        "promosyon/yeni/",
        panel_views.panel_promo_edit,
        name="panel_promo_new",
    ),
    path(
        "promosyon/<int:promo_id>/",
        panel_views.panel_promo_edit,
        name="panel_promo_edit",
    ),
    path(
        "promosyon/<int:promo_id>/sil/",
        panel_views.panel_promo_delete,
        name="panel_promo_delete",
    ),
    path(
        "promosyon/<int:promo_id>/toggle/",
        panel_views.panel_promo_toggle,
        name="panel_promo_toggle",
    ),
    path(
        "konu/<int:topic_id>/",
        panel_views.panel_topic,
        {"tab": "lessons"},
        name="panel_topic_home",
    ),
    path(
        "konu/<int:topic_id>/<str:tab>/",
        panel_views.panel_topic,
        name="panel_topic",
    ),
]
