from django.urls import path

from .views import (
    AnnouncementListView,
    ContentCatalogView,
    ContentPackVersionView,
    ContentPackView,
    CurriculumView,
    DeviceTokenView,
    GoogleAuthView,
    HealthView,
    MeMessagesView,
    MeView,
    PublishedQuestionsView,
    PublishedTestsView,
    QuestionRatingView,
    QuestionErrorReportView,
    SimilarQuestionsView,
    DailyMiniExamView,
    ExamPackDetailView,
    ExamPackExamQuestionsView,
    ExamPackListView,
    ExamTypeListView,
    PromoRedeemView,
    TestQuestionsView,
    TestAttemptView,
    QuestionAttemptView,
)

urlpatterns = [
    path("health/", HealthView.as_view(), name="health"),
    path("pack/", ContentPackView.as_view(), name="content-pack"),
    path("pack/version/", ContentPackVersionView.as_view(), name="content-pack-version"),
    path("catalog/", ContentCatalogView.as_view(), name="content-catalog"),
    path("curriculum/", CurriculumView.as_view(), name="curriculum"),
    path("questions/", PublishedQuestionsView.as_view(), name="questions"),
    path(
        "questions/<str:public_id>/similar/",
        SimilarQuestionsView.as_view(),
        name="question-similar",
    ),
    path(
        "questions/<str:public_id>/rating/",
        QuestionRatingView.as_view(),
        name="question-rating",
    ),
    path(
        "questions/<str:public_id>/attempt/",
        QuestionAttemptView.as_view(),
        name="question-attempt",
    ),
    path(
        "questions/<str:public_id>/error-report/",
        QuestionErrorReportView.as_view(),
        name="question-error-report",
    ),
    path("tests/", PublishedTestsView.as_view(), name="tests"),
    path(
        "tests/<str:test_id>/questions/",
        TestQuestionsView.as_view(),
        name="test-questions",
    ),
    path(
        "tests/<str:test_id>/attempt/",
        TestAttemptView.as_view(),
        name="test-attempt",
    ),
    path("announcements/", AnnouncementListView.as_view(), name="announcements"),
    path("device-tokens/", DeviceTokenView.as_view(), name="device-tokens"),
    path("auth/google/", GoogleAuthView.as_view(), name="auth-google"),
    path("me/", MeView.as_view(), name="me"),
    path("me/messages/", MeMessagesView.as_view(), name="me-messages"),
    path("daily-mini-exam/", DailyMiniExamView.as_view(), name="daily-mini-exam"),
    path("promo/redeem/", PromoRedeemView.as_view(), name="promo-redeem"),
    path("exam-types/", ExamTypeListView.as_view(), name="exam-types"),
    path("exam-packs/", ExamPackListView.as_view(), name="exam-packs"),
    path(
        "exam-packs/<str:pack_id>/",
        ExamPackDetailView.as_view(),
        name="exam-pack-detail",
    ),
    path(
        "exam-packs/<str:pack_id>/exams/<int:exam_index>/questions/",
        ExamPackExamQuestionsView.as_view(),
        name="exam-pack-exam-questions",
    ),
]
